name: Deploy

on:
  push:
    branches: "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        run: git submodule update --init --recursive
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'
          extended: true
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.5.2
        with:
            ssh-private-key: ${{ secrets.IMMATHAN_SSH_KEY }}
      - name: Deploy
        run: |
          chmod +x deploy.sh
          ./deploy.sh "${{ secrets.GITHUB_TOKEN }}"